name: Unit Test

# Controls when the action will run.
on: [ pull_request ]

jobs:
  test:
    name: Simple unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: EggheadsSolutions/ci-php-unit-test@v1
        with:
          mysql: 'yes'
          redis: 'no'
          clickhouse: 'no'
          config-dir: 'test-app-conf'
          additional-parameters: '--exclude-group Git'
          npm-packages: sass postcss postcss-cli autoprefixer

