name: Unit Test

# Controls when the action will run.
on: [ push ]

jobs:
  test:
    name: Simple unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: EggheadsSolutions/php-unit-test@v1
        with:
          mysql: 'no'
          redis: 'no'
          clickhouse: 'no'
          use-repository-config: 'no'
          app-local-php: 'no'
          additional-parameters: '-exclude-group Git'
